name = "puck"
version = "0.1.0"

[dependencies]
gleam_stdlib = "~> 0.19"
gleam_hackney = "~> 0.2"
gleam_http = "~> 3.0"
gleam_json = "~> 0.4"
gleam_erlang = "~> 0.9"
gleam_bbmustache = "~> 2.0"
gleam_otp = "~> 0.3"
gleam_crypto = "~> 0.3"
zeptomail = "~> 0.1"
mist = "~> 0.9"
sqlight = "~> 0.5"
bcrypt = "~> 1.1"

[dev-dependencies]
gleeunit = "~> 0.6"
